# Generated by Django 4.2.6 on 2024-01-09 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catagyres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentType', models.CharField(choices=[('CASH', 'CASH'), ('VISA', 'VISA')], default='CASH', max_length=20)),
                ('addUser', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tablemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('tableDetial', models.CharField(max_length=240, verbose_name='Name')),
                ('status_Busy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catagyres.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderOftable.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='orderOftable.OrderItem', to='catagyres.item'),
        ),
        migrations.AddField(
            model_name='order',
            name='tableNumber',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_no', to='orderOftable.tablemodel'),
        ),
    ]
