# Generated by Django 4.2.6 on 2024-01-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderOftable', '0002_remove_order_items_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tableNumber',
        ),
    ]
