# Generated by Django 4.2.6 on 2024-01-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
