# Generated by Django 4.2.6 on 2024-01-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catagyres', '0001_initial'),
        ('orderOftable', '0003_remove_order_client_remove_order_tablenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopcart_books', to='catagyres.item')),
            ],
        ),
        migrations.CreateModel(
            name='EndOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalcost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentType', models.CharField(choices=[('CASH', 'CASH'), ('VISA', 'VISA')], default='CASH', max_length=20)),
                ('adduser', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itemsorders', models.ManyToManyField(to='cart.shopcart')),
                ('tableNumber', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_no', to='orderOftable.tablemodel')),
            ],
        ),
    ]
