# Generated by Django 4.2.6 on 2024-01-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorder',
            name='orderedfinish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='cartno',
            field=models.BigIntegerField(default=1),
        ),
    ]
