# Generated by Django 4.2.6 on 2024-01-14 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagyres', '0001_initial'),
        ('cart', '0002_endorder_orderedfinish_shopcart_cartno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopCart',
            new_name='Cart',
        ),
    ]
