# Generated by Django 4.2.6 on 2024-01-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_shopcart_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cartn',
            field=models.BigIntegerField(default=1),
        ),
    ]
