# Generated by Django 4.2.6 on 2024-01-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordercart', '0003_alter_ordercart_cartid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='cartid',
        ),
    ]
