# Generated by Django 4.2.6 on 2024-01-15 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderOftable', '0003_remove_order_client_remove_order_tablenumber'),
        ('ordercart', '0004_remove_ordercart_cartid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercart',
            name='orderstate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordercart',
            name='t_number',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_tableno', to='orderOftable.tablemodel'),
            preserve_default=False,
        ),
    ]
